name: Publish

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Logseq Publish
        uses: logseq/publish-spa@main

      - name: Add .nojekyll file
        run: touch www/.nojekyll

      - name: Fix permissions
        run: |
          chmod -c -R +rX dist/

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: www